title: Mehmet ONAR
author:
  name: mhmtonrn
  email: mhmronar1@gmail.com
  
description: > # this means to ignore newlines until "show_excerpts:"
  Github

minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: jekyllrb
    github:  jekyll

markdown: kramdown
theme: minima
